/**
 * Every user-facing string of the web client, in one flat object so the app can be translated
 * later. Placeholders in braces (`{name}`) are filled with `fmt()` from `./lib/format`.
 */
export const strings = {
  // App / top bar
  appName: 'Landlord',
  pitch:
    'Fight the Landlord with friends in your browser. Share a link, fill empty seats with bots.',
  roomCode: 'Room {code}',
  leave: 'Leave',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  chat: 'Chat',
  openChat: 'Open chat',
  closeChat: 'Close chat',
  unread: '{count} unread',

  // Connection
  connecting: 'Connecting...',
  reconnecting: 'Reconnecting...',
  errorTitle: 'Something went wrong',
  dismiss: 'Dismiss',

  // Home
  yourName: 'Your name',
  namePlaceholder: 'Enter your name',
  createRoomTitle: 'Create a room',
  createRoomButton: 'Create room',
  creatingRoom: 'Creating room...',
  joinRoomTitle: 'Join a room',
  joinCodeLabel: 'Room code',
  joinCodePlaceholder: 'ABC123',
  joinRoomButton: 'Join',
  howToPlay: 'How to play',
  rulesPageTitle: 'How to play',

  // Rule options
  optPlayerCount: 'Players',
  optPlayerCountHelp: 'Three players use one deck, four players use two decks.',
  optKittySize: 'Kitty size',
  optKittySizeHelp: 'Face-down cards the Landlord picks up. The rest is dealt evenly.',
  optBiddingMode: 'Bidding style',
  optBiddingModeHelp: 'Call: say yes or pass, then others may rob. Points: bid 1, 2 or 3.',
  optBiddingCall: 'Call',
  optBiddingPoints: 'Points',
  optAllPass: 'If everyone passes',
  optAllPassHelp: 'Force the last bidder to be the Landlord, or reshuffle and deal again.',
  optAllPassForce: 'Force last bidder',
  optAllPassRedeal: 'Redeal',
  optDoubling: 'Doubling round',
  optDoublingHelp: 'After the kitty is revealed everyone may secretly double their stake.',
  optKittyBonus: 'Kitty bonus',
  optKittyBonusHelp: 'A lucky kitty (jokers, a run, three of a kind) multiplies the stake.',
  optFirstBidder: 'First bidder',
  optFirstBidderHelp: 'Who starts the bidding on later hands.',
  optFirstBidderWinner: 'Previous winner',
  optFirstBidderRotate: 'Rotate',
  optFirstBidderRandom: 'Random',
  optChains: 'Chains may include 2s and jokers',
  optChainsHelp: 'Straights and airplanes may run past the Ace: Q K A 2 Joker. Off uses 3 to A.',
  optTurnSeconds: 'Turn timer',
  optTurnSecondsHelp: 'Seconds to make each decision before the game decides for you.',
  seconds: '{n} s',
  cards: '{n} cards',
  on: 'On',
  off: 'Off',
  players: '{n} players',

  // Room / lobby
  joiningRoom: 'Joining room {code}...',
  roomNotFound: 'That room does not exist or has closed.',
  joinFailed: 'Could not join room {code}.',
  retry: 'Retry',
  backHome: 'Back to the home page',
  shareTitle: 'Invite friends',
  shareHelp: 'Send this link. Anyone who opens it joins the lobby.',
  copyLink: 'Copy link',
  copied: 'Copied!',
  shareLink: 'Share',
  seatsTitle: 'Seats',
  emptySeat: 'Empty seat',
  sitHere: 'Sit here',
  standUp: 'Stand up',
  addBot: 'Add bot',
  removeBot: 'Remove',
  kick: 'Kick',
  kickName: 'Kick {name}',
  kickConfirm: 'Kick {name}? A bot will play their seat for the rest of the room.',
  leaveConfirm: 'Leave the table? A bot will take your seat for the rest of this room.',
  fillWithBots: 'Fill with bots',
  bot: 'Bot',
  host: 'Host',
  you: 'You',
  away: 'Away',
  startHand: 'Start hand',
  nextHand: 'Next hand',
  waitingForHost: 'Waiting for the host to start',
  waitingForSeats: 'Fill every seat to start',
  spectatorsTitle: 'Watching',
  noSpectators: 'Nobody is watching',
  rulesTitle: 'Options',
  editOptions: 'Edit options',
  saveOptions: 'Save options',
  cancel: 'Cancel',
  scoreboard: 'Scores',
  handNumber: 'Hand {n}',
  handsPlayed: '{n} hands played',
  handPlayedOne: '1 hand played',
  chipPlayers: '{n} players',
  chipKitty: 'Kitty {n}',
  chipBiddingCall: 'Call / Rob',
  chipBiddingPoints: 'Bid 1-2-3',
  chipAllPassForce: 'Force last bidder',
  chipAllPassRedeal: 'Redeal on all pass',
  chipDoubling: 'Doubling round',
  chipKittyBonus: 'Kitty bonus',
  chipFirstBidderWinner: 'Winner bids first',
  chipFirstBidderRotate: 'Rotate first bidder',
  chipFirstBidderRandom: 'Random first bidder',
  chipChains: 'Chains through 2s',
  chipChainsOff: 'Chains up to A',
  chipTimer: '{n} s timer',

  // Table
  landlord: 'Landlord',
  peasant: 'Peasant',
  yourLead: 'Your lead',
  leads: '{name} leads',
  playedBy: '{name} played',
  pass: 'Pass',
  passed: 'Passed',
  stake: 'Stake x{n}',
  kitty: 'Kitty',
  yourTurn: 'Your turn',
  waitingFor: 'Waiting for {name}',
  youAreWatching: 'You are watching',
  sit: 'Sit',
  bidding: 'Bidding',
  doubling: 'Doubling round',
  doublingWaiting: 'Waiting for {n} players',
  doublingWaitingOne: 'Waiting for 1 player',
  doublingDone: 'Everyone has decided',
  doublingWaitingUnknown: 'Waiting for players to decide',
  youDoubled: 'You doubled',
  youKept: 'You kept',
  doubledBadge: 'x2',
  bidCalled: '{name} called',
  bidRobbed: '{name} robbed',
  bidPassed: '{name} passed',
  bidPoints: '{name} bid {value}',
  landlordChosen: '{name} is the Landlord',
  landlordEveryoneElsePassed: 'Everyone else passed, so {name} is the Landlord',
  landlordEveryonePassed: 'Everyone passed, so {name} is the Landlord',
  redealNotice: 'Everyone passed. New cards were dealt.',
  cardsLeft: '{n} left',
  oneCardLeft: '1 left',
  disconnected: 'Disconnected',
  timeLeft: '{n} seconds left',
  hint: 'Hint',
  play: 'Play',
  clear: 'Clear',
  call: 'Call',
  rob: 'Rob',
  keep: 'Keep',
  double: 'Double',
  bidValue: '{value}',
  selectCards: 'Tap cards to select them',
  notValidPlay: 'Not a valid play',
  doesNotBeat: "Doesn't beat the {combo}",
  noPlayBeats: 'Nothing in your hand beats this',
  comboSingle: 'Single {rank}',
  comboPair: 'Pair of {rank}s',
  comboTriple: 'Triple {rank}s',
  comboTripleSingle: 'Triple {rank}s + single',
  comboTriplePair: 'Triple {rank}s + pair',
  comboChainTo: '{name} to {rank}',
  comboBomb: 'Bomb of {rank}s',
  comboRocket: 'Rocket',
  cardBack: 'Face-down card',
  redJoker: 'Red Joker',
  blackJoker: 'Black Joker',
  joker: 'JOKER',
  cardLabel: '{rank} of {suit}',
  suitSpades: 'spades',
  suitHearts: 'hearts',
  suitDiamonds: 'diamonds',
  suitClubs: 'clubs',
  yourHand: 'Your hand',
  yourHandEmpty: 'No cards',
  playedCards: 'Played cards',

  // Result
  resultTitle: 'Hand {n} over',
  landlordWins: 'The Landlord wins',
  peasantsWin: 'The Peasants win',
  youWin: 'You win!',
  youLose: 'You lose',
  breakdownBase: 'Base stake',
  breakdownRobs: 'Robs: {n}',
  breakdownBombs: 'Bombs: {n}',
  breakdownSpring: 'Spring',
  breakdownAntiSpring: 'Anti-spring',
  breakdownKittyBonus: 'Kitty bonus',
  breakdownStake: 'Final stake',
  breakdownDoubled: '{name} doubled',
  multiplier: 'x{n}',
  pointsPlus: '+{n}',
  pointsMinus: '-{n}',
  runningScore: 'Running score',
  wentOut: '{name} went out first',

  // Chat
  chatTitle: 'Chat',
  chatPlaceholder: 'Say something...',
  send: 'Send',
  emotes: 'Emotes',
  chatEmpty: 'No messages yet',
  chatSlowDown: 'Slow down a moment',
  sendEmote: 'Send {emote}',

  // Rules page
  rulesHeader: 'Landlord',
  rulesSubtitle: 'Rules of the game',
} as const;

export type StringKey = keyof typeof strings;
